name: Twitch Chat Stream
language: python
variables:
  - name: Topic
    inputType: OutputTopic
    description: Name of the output topic to write into
    defaultValue: messages
    required: true
  - name: TwitchToken
    inputType: HiddenText
    description: Needed for auth
    defaultValue: oauth:01qiyvmqb86s8tw18bovr81i52xerr
    required: true
  - name: TwitchAppClientId
    inputType: HiddenText
    description: ''
    defaultValue: elqo0jjhhzxyat9mhtniuowdj0tipj
    required: true
  - name: TwitchAppClientSecret
    inputType: HiddenText
    description: ''
    defaultValue: ifb1km2w404mtcbh2s7moewiud77bs
    required: true
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
