name: Twitch Chat Stream
language: python
variables:
  - name: Topic
    inputType: OutputTopic
    description: Name of the output topic to write into
    defaultValue: messages
    required: true
  - name: TwitchChannel
    inputType: FreeText
    description: Twitch channel name
    defaultValue: nmplol
    required: true
  - name: TwitchNickname
    inputType: FreeText
    description: Needed for auth
    defaultValue: quixdemo
    required: true
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
