name: Twitch Chat Stream
language: python
variables:
  - name: Topic
    inputType: OutputTopic
    description: Name of the output topic to write into
    defaultValue: messages
    required: true
  - name: TwitchToken
    inputType: HiddenText
    description: Needed for auth
    defaultValue: oauth:01qiyvmqb86s8tw18bovr81i52xerr
    required: true
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
