name: Message counter
language: python
variables:
  - name: Topic
    inputType: InputTopic
    description: ''
    defaultValue: messages
    required: false
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
