name: Sentiment analysis 2
language: python
variables:
  - name: drafts
    inputType: InputTopic
    description: 'Unsent draft messages '
    defaultValue: ''
    required: true
  - name: output
    inputType: OutputTopic
    description: This is the output for the Hugging Face model score
    defaultValue: sentiment
    required: true
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: quix_function.py
