name: Twitch Chat
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write messages into
    defaultValue: messages
    required: true
  - name: StreamsToJoinCount
    inputType: FreeText
    description: Number of active stream channel to constantly be connected to
    defaultValue: 100
    required: true
  - name: TwitchAppClientId
    inputType: Secret
    description: ''
    defaultValue: TwitchAppClientId
    required: true
  - name: TwitchAppClientSecret
    inputType: Secret
    description: ''
    defaultValue: TwitchAppClientSecret
    required: true
  - name: TwitchBotToken
    inputType: Secret
    description: ''
    defaultValue: TwitchBotToken
    required: true
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
