name: Twitch Chat
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: This is the output topic for hello world data
    defaultValue: messages
    required: true
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
